spring:
  application:
    name: catalog-service

  autoconfigure:
    exclude:
      - com.commerceos.tenant.context.TenantContextAutoConfiguration

  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: commerce
    password: commerce
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    mongodb:
      uri: mongodb://commerce:commerce@localhost:27017/catalog_web_commerce?authSource=admin
      auto-index-creation: false
    redis:
      host: localhost
      port: 6379
      password: commerce
      timeout: 2000ms

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: catalog-opensearch-indexer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.commerceos.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: "java.util.Map"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

server:
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.commerceos: DEBUG
