CREATE DATABASE auth_db;
CREATE DATABASE platform_admin_db;
CREATE DATABASE provisioning_db;
CREATE DATABASE notification_db;
CREATE DATABASE tax_db;
CREATE DATABASE billing_db;
CREATE DATABASE payment_adapter_db;
CREATE DATABASE ledger_db;
CREATE DATABASE inventory_db;
CREATE DATABASE catalog_db;
CREATE DATABASE order_db;
CREATE DATABASE seller_db;
CREATE DATABASE temporal;
CREATE DATABASE temporal_visibility;

GRANT ALL PRIVILEGES ON DATABASE auth_db TO commerce;
GRANT ALL PRIVILEGES ON DATABASE platform_admin_db TO commerce;
GRANT ALL PRIVILEGES ON DATABASE provisioning_db TO commerce;
GRANT ALL PRIVILEGES ON DATABASE notification_db TO commerce;
GRANT ALL PRIVILEGES ON DATABASE tax_db TO commerce;
GRANT ALL PRIVILEGES ON DATABASE billing_db TO commerce;
GRANT ALL PRIVILEGES ON DATABASE payment_adapter_db TO commerce;
GRANT ALL PRIVILEGES ON DATABASE ledger_db TO commerce;
GRANT ALL PRIVILEGES ON DATABASE inventory_db TO commerce;
GRANT ALL PRIVILEGES ON DATABASE catalog_db TO commerce;
GRANT ALL PRIVILEGES ON DATABASE order_db TO commerce;
GRANT ALL PRIVILEGES ON DATABASE seller_db TO commerce;
GRANT ALL PRIVILEGES ON DATABASE temporal TO commerce;
GRANT ALL PRIVILEGES ON DATABASE temporal_visibility TO commerce;
